config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users do
    resources :favorite_listings, only: [:create, :destroy]
  end
  resources :listings
  root 'listings#index'

  get '/about', to: 'static_pages#about'
  get '/policies', to: 'static_pages#policies'
  get '/utilities', to: 'static_pages#utilities'
  get '/contact', to: 'static_pages#contact'
  get '/users/:id', to: 'users#show', as: 'profile'

  resources :favorite_listings, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :listing
  attachment :file
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :images, dependent: :destroy
  accepts_attachments_for :images, append: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
  has_many :favorite_listings, through: :favorites, source: :favorited, source_type: 'Listing'

  # Mailboxer
  acts_as_messageable

  def mail_email(object)
    email
  end

  def name
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt   = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end

end

app/controllers/favorite_listings_controller.rb
class FavoriteListingsController < ApplicationController
  before_action :set_listing

  def create
    if Favorite.create(favorited: @listing, user: current_user)
      redirect_to :back
    else
      redirect_to :back, alert: 'Something has gone terribly wrong...'
    end
  end

  def destroy
    Favorite.where(favorited_id: @listing.id, user_id: current_user.id).first.try(:destroy)
    redirect_to :back
  end

  private
  def set_listing
    @listing = Listing.find(params[:format] || params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to :back
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource except: [:create]

  def index
    @search = Listing.ransack(params[:q])
    @listings = @search.result.page(params[:page])

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listings_params)
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @listing.update(listings_params)
        format.html { redirect_to @listing }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path
  end

  private

  def listings_params
    params.require(:listing).permit(:title, :description, :address, :bed, :bath, :half_bath, :square_foot, :max_price, :min_price, :image, :appliances, :features, :schools, :pets, :property_type, images_files: [])
  end

  def find_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation
  before_action :authenticate_user!

  def create
    receipt = current_user.reply_to_conversation(@conversation, params[:body])
    redirect_to conversation_path(receipt.conversation)
  end

  private

  def set_conversation
    @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def policies
  end

  def utilities
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @favorite_listings = @user.favorite_listings.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/conversations/index.html.erb
<% @conversations.each do |conversation| %>
  <div class="">
    <%= link_to conversation.subject, conversation_path(conversation) %>
  </div>
<% end %>

<%= link_to "New Conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <div class="">
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
  </div>

  <div class="">
    <%= text_field_tag :subject, nil, placeholder: "Subject" %>
  </div>

  <div class="">
    <%= text_field_tag :body, nil, placeholder: "Body" %>
  </div>

  <%= submit_tag %>

<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
  <div class="">
    <%= receipt.message.sender.email %> said:<br>
    <%= receipt.message.body %><br>
  </div>
<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
  <div class="">
    <%= text_area_tag :body %>
  </div>
  <%= submit_tag %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rental Listings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>

  <div class="container">

    <div class="">
      <% if notice %><p class="alert alert-notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert alert-warning"><%= alert %></p><% end %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, html: { multipart: true } do |f| %>
  <div class='col-md-12'>
    <div class='images-container'>
      <% @listing.images.each do |i| %>
        <div class='form-image'>
          <%= image_tag attachment_url(i, :file, :fit, 200, 130) %>
          <div class='delete-image'>
            <%= link_to image_path(i.id), method: :delete do %>
              <span class='glyphicon glyphicon-remove' title='remove image'></span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class='form-group'>
      <%= f.label :images_files, "Upload Pictures:" %>
      <%= f.attachment_field :images_files, class: 'form-control', multiple: true %>
    </div>
    <div class='form-group'>
      <%= f.label :title %>:
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :property_type %>
      <%= f.select :property_type, ["Apartment", "Studio", "House", "Other"] %>
    </div>
    <div class="form-group">
      <%= f.label :pets %>
      <%= f.select :pets, ["None", "OK", "Dogs Only", "Cats Only"] %>
    </div>
    <div class='form-group'>
      <%= f.label :address %>:
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <div class='col-md-6'>
      <%= f.label :max_price, "Max Price" %>:
      <%= f.text_field :max_price, class: 'form-control' %>
    </div>
    <div class='col-md-6'>
      <%= f.label :min_price, "Min Price:" %>
      <%= f.text_field :min_price, class: 'form-control' %>
  </div>
  <div class='col-md-12'>
    <div class='form-group'>
      <%= f.label :bed, "Bedrooms" %>:
      <%= f.text_field :bed, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :bath %>:
      <%= f.text_field :bath, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :half_bath %>:
      <%= f.text_field :half_bath, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :square_foot %>:
      <%= f.text_field :square_foot, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :appliances, "Appliances (separate with commas)" %>:
      <%= f.text_field :appliances, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :features, "Features (separate with commas)" %>:
      <%= f.text_field :features, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :schools %>:
      <%= f.text_field :schools, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :description %>:
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary"%>
    <%= link_to "Cancel", root_path, class: 'btn btn-default', role: 'button' %>
  </div>
<% end %>

app/views/listings/_image_slider.html.erb
<div class='images-container row'>
  <div class='listing-images-slider'>
    <% @listing.images.each do |i| %>
      <%= image_tag attachment_url(i, :file, :fill, 300, 200) %>
    <% end %>
  </div>
</div>

app/views/listings/_listing.html.erb
    <div class='listing-container'>
      <div class='image-container'>
        <% if l.images %>
          <%= link_to (image_tag attachment_url(l.images[0], :file, :fill, 300, 170)), l %>
          <div class='images-badge'>
            <span class='badge'><%= l.images.count %> <span class='glyphicon glyphicon-camera'></span></span>
          </div>
        <% end %>
      </div>
      <div class='listing-details'>
        <span class='listing-title'><%= link_to l.title, l %></span>
        <span class='listing-street-address'><%= l.address %></span>
        <span class='listing-price'><b>
          <% if l.min_price && l.max_price %>
            $<%= l.min_price %>+
          <% else %>
            $<%= l.max_price || l.min_price %>
          <% end %>
          </b>/ month
        </span>
        <span class='listed-details'>
          <b><%= l.bed %></b> Bd -
          <b><%= l.bath + l.half_bath.to_i %></b> Ba -
          <b><%= l.square_foot %>+</b> sq ft -
          <b>Pets</b> <%= l.pets %>
        </span>
        <br>
      </div>
      <div class='favorite-listing-button'>
        <%= render '/shared/favorite_listing', listing: l %>
      </div>
      <div class='view-property-button'>
        <%= link_to "View Details", l, class: 'btn btn-danger', role: 'button' %>
      </div>
    </div>

app/views/listings/_listings.html.erb
<% if @listings.length > 0 %>
  <% @listings.each do |l| %>
    <%= render 'listing',  l: l %>
  <% end %>
<% else %>
  <span>No listings were found :(</span>
<% end %>
<div class='pull-right'>
  <%= paginate @listings, remote: true %>
</div>

app/views/listings/_search_form.html.erb
<div class='listing-search row'>
  <div class="col-12">
    <%= search_form_for @search, class: 'form-inline float-right', remote: true do |f| %>
      <!-- Searches addresses. Move to nav bar or remove -->
      <!-- <div class="col">
        <div class='form-group'>
          <%= f.label :address_cont, "Search for Listing", class: 'sr-only' %>
          <%= f.text_field :address_cont, placeholder: 'Search', class: 'form-control' %>
        </div>
      </div> -->
      <div class='form-group pr-sm-3'>
        <%= f.label :max_price_gteq, "Price Range", class: 'navbar-text pr-sm-2' %>
        <%= f.text_field :max_price_gteq, placeholder: 'Min', class: 'form-control' %>
        <%= f.text_field :max_price_lteq, placeholder: 'Max', class: 'form-control' %>
      </div>
      <div class='form-group pr-sm-3'>
        <%= f.label :bed_gteq, "Beds", class: 'navbar-text pr-sm-1' %>
        <%= f.select :bed_gteq, (1..5) %>
      </div>
      <div class='form-group pr-sm-3'>
        <%= f.label :bath_gteq, "Baths", class: 'navbar-text pr-sm-1' %>
        <%= f.select :bath_gteq, (1..5) %>
      </div>
      <div class='form-group'>
        <%= f.submit "Search", class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/edit.html.erb
<div class="page-header">
  <h1><%= @listing.title %></h1>
</div>
<%= render 'form' %>

app/views/listings/index.html.erb
<%= render 'search_form' %>
<div class="row">

  <div class='col-12'>
    <div class='listing-region'>
      <h3>Clemson, SC Apartments and Homes for Rent</h3>
      <% if can? :manage, @listing %>
        <%= link_to new_listing_path do %>
          <span class='glyphicon glyphicon-plus'></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div id='listings-container' class='col-12'>
    <%= render 'listings' %>
  </div>
</div>

app/views/listings/index.js.erb
$('#listings-container').html("<%= j render 'listings' %>");

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/listings/show.html.erb
<div class='full-listing-container'>
  <header class='col-lg-9'>
    <h2><%= @listing.title %><span class='pull-right'>
      <% if @listing.min_price && @listing.max_price %>
        $<%= @listing.min_price %> - $<%= @listing.max_price %>
      <% else %>
        $<%= @listing.max_price || @listing.min_price %>
      <% end %></span>
    </h2>
    <span class='listing-address'><%= @listing.address %></span>
  </header>
  <aside class='col-lg-3 pull-right property-icons sidebar'>
    <div class='inline-buttons'>
      <%= render '/shared/favorite_listing', listing: @listing %>
      <% if can? :manage, @listing %>
        <%= link_to "Edit", edit_listing_path, class: 'btn btn-default' %>
        <%= link_to "Delete", listing_path(@listing), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default' %>
      <% end %>
    </div>
    <div class='sidebar-form section'>
      <%= render '/shared/more_info' %>
    </div>
  </aside>
  <div class='col-lg-9 listing-body'>
    <p>
      <b><%= @listing.bed %></b> Beds -
      <b><%= @listing.bath %></b> Baths -
      <b>Pets</b> <%= @listing.pets %> -
      <% unless @listing.half_bath.nil? || @listing.half_bath == 0 %><b><%= @listing.half_bath %></b> Half Baths -<% end %>
      <% if @listing.square_foot %>
        <b><%= @listing.square_foot %>+</b> sq. feet
      <% else %>
        <b>Square Footage Unavailable</b>
      <% end %>
    </p>
    <%= render 'image_slider' %>
    <div class='property-details'>
      <div class='details-header row'>
        <h3>Property Details</h3>
      </div>
      <div class='details-section row'>
        <div class='description'>
          <div class='col-md-3 col-lg-2 section-label'>
            <span>Description</span>
          </div>
          <div class='col-md-9 col-lg-10 section-body'>
            <span><%= @listing.description %></span>
          </div>
        </div>
      </div>
      <div class='details-section row'>
        <div class='schools'>
          <div class="col-md-3 col-lg-2 section-label">
            <span>Schools</span>
          </div>
          <div class='col-md-9 col-lg-10 section-body'>
            <% if @listing.schools %>
                <ul class='list-default'>
                <% @listing.schools.split(',').each do |a| %>
                  <li><%= a %></li>
                <% end %>
                </ul>
            <% end %>
          </div>
        </div>
      </div>
      <div class='details-section row'>
        <div class='appliances'>
          <div class="col-md-3 col-lg-2 section-label">
            <span>Appliances</span>
          </div>
          <div class='col-md-9 col-lg-10 section-body'>
            <% if @listing.appliances %>
              <% @listing.appliances.split(',').in_groups(2, false).each do |arr| %>
                <div class='col-lg-6 no-indent'>
                  <ul class='list'>
                    <% arr.each do |a| %>
                      <li><%= a %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class='details-section row last'>
        <div class='features'>
          <div class="col-md-3 col-lg-2 section-label">
            <span>Features</span>
          </div>
          <div class='col-md-9 col-lg-10 section-body'>
            <% if @listing.features %>
              <% @listing.features.split(',').in_groups(2, false).each do |arr| %>
                <div class='col-lg-6 no-indent'>
                  <ul class='list'>
                    <% arr.each do |a| %>
                      <li><%= a %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div> <!-- end of panel -->
  </div>
</div>

app/views/shared/_favorite_listing.html.erb
<div class='favorite-listing'>
  <% if current_user %>
    <% unless current_user.favorite_listings.include?(listing) %>
      <%= link_to favorite_listings_path(listing), method: :post do %>
        <span class='glyphicon glyphicon-heart' title='Add to favorites'></span>
      <% end %>
    <% else %>
      <%= link_to favorite_listing_path(listing), method: :delete do %>
        <span class='glyphicon glyphicon-heart favorited' title='Remove from favorites'></span>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to new_user_registration_path do %>
      <span class='glyphicon glyphicon-heart'></span>
    <% end %>
  <% end %>
</div>

app/views/shared/_more_info.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Subject</label>
    <input class="form-control" id="exampleInputPassword1" placeholder="Subject">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Your Message</label>
    <input type='text' class="form-control" id="exampleInputPassword1" placeholder="Write some stuff here...">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <button type="submit" class="btn btn-danger">Submit</button>
</form>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <%= link_to "Clemson Rentals", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class='nav-item <%= 'active' if current_page?(root_path)%>'>
          <%= link_to "All Listings", root_path, class: 'nav-link' %>
        </li>
        <li class='nav-item <%= 'active' if current_page?(about_path)%>'>
          <%= link_to "About", about_path, class: 'nav-link' %>
        </li>
        <li class='nav-item <%= 'active' if current_page?(policies_path)%>'>
          <%= link_to "Policies", policies_path, class: 'nav-link' %>
        </li>
        <li class='nav-item <%= 'active' if current_page?(utilities_path)%>'>
          <%= link_to "Utilities", utilities_path, class: 'nav-link' %>
        </li>
        <li class='nav-item <%= 'active' if current_page?(contact_path)%>'>
          <%= link_to "Contact", contact_path, class: 'nav-link' %>
        </li>

        <% if current_user %>
        <!-- User info -->
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", profile_path(current_user), class: 'dropdown-item' %>
            <%= link_to "Account Settings", edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
        <% else %>
        <!-- Sign in/up -->
        <li><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
        <li><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
  </nav>

app/views/static_pages/about.html.erb
<div class='page-header'>
  <h1>About Clemson Rentals</h1>
</div>
<div>
  <p>Clemson Rentals is a property management system for properties in the Clemson area.
</div>

app/views/static_pages/contact.html.erb
<h1>Contact Clemson Rentals</h1>

app/views/static_pages/policies.html.erb
<h1>Policies</h1>

app/views/static_pages/utilities.html.erb
<h1>Utilites for Clemson Rentals' Properties</h1>

app/views/users/show.html.erb
<div class='page-header'>
  <h2><%= @user.email %>'s Page</h2>
</div>
<h3>My Favorited Listings</h3>

<div id='listings-container' class='col-lg-12'>
  <% if @favorite_listings.length > 0 %>
    <% @favorite_listings.each do |l| %>
      <%= render '/listings/listing', l: l %>
    <% end %>
  <% else %>
    <span>You don't have any favorites yet.</span>
  <% end %>
  <div class='pull-right'>
    <%= paginate @favorite_listings, remote: true %>
  </div>
</div>